In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('homeprices.csv')
df.head()

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [3]:
na = df.bedrooms.median()

In [4]:
df = df.fillna(na)

In [5]:
x = df.drop('price', axis=1)

In [6]:
lreg = LinearRegression()

In [7]:
lreg.fit(x, df.price)

LinearRegression()

In [8]:
lreg.predict([[3000,3,40]])

array([498408.25158031])

In [9]:
lreg.predict([[2500,4,5]])

array([578876.03748933])

# test

In [40]:
test_df = pd.read_csv('test.csv')
test_df.head()

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000

In [41]:
test_df['experience'] = test_df['experience'].fillna('zero')

In [42]:
test_df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [43]:
from word2number import w2n

In [44]:
test_df['experience'] = test_df['experience'].apply(w2n.word_to_num)

In [45]:
from math import floor

In [49]:
test_df['test_score(out of 10)'] = \
        test_df['test_score(out of 10)'].fillna(floor(test_df['test_score(out of 10)'].mean()))

In [53]:
x = test_df.drop(['salary($)'], axis=1)

In [54]:
model = LinearRegression()
model.fit(x, test_df['salary($)'])

LinearRegression()

In [55]:
model.predict([[2,9,6]])

array([53713.86677124])

In [56]:
model.predict([[12,10,10]])

array([93747.79628651])