In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [2]:
from sklearn.model_selection import train_test_split

In [3]:
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.2)

In [4]:
from sklearn.model_selection import KFold

In [5]:
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [6]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train,y_train)
    return model.score(X_test, y_test)

In [7]:
for train_index, test_index in kf.split(digits.data, digits.target):
    train_index, test_index

In [8]:
get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test)

0.975

In [9]:
get_score(SVC(), X_train, X_test, y_train, y_test )

0.9972222222222222

In [10]:
get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test)

0.9805555555555555

In [11]:
from sklearn.model_selection import StratifiedKFold

In [12]:
fold = StratifiedKFold(n_splits=3)
scores_logistic = []
scores_svm = []
scores_rf = []

In [37]:
for train_index, test_index in kf.split(digits.data, digits.target):
    
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(max_iter=10000), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(), X_train, X_test, y_train, y_test))

CPU times: user 27.1 s, sys: 2.92 s, total: 30 s
Wall time: 5.42 s


In [14]:
scores_logistic

[0.9282136894824707, 0.9415692821368948, 0.9165275459098498]

In [15]:
scores_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [16]:
scores_rf

[0.9332220367278798, 0.9532554257095158, 0.9282136894824707]

In [18]:
from sklearn.model_selection import cross_val_score

In [30]:
cross_val_score(LogisticRegression(max_iter=10000), digits.data, digits.target,cv=3)

array([0.92487479, 0.93989983, 0.92320534])

In [22]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [28]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=2)

array([0.90322581, 0.93095768])

In [36]:
%%time
cross_val_score(LogisticRegression(max_iter=10000), digits.data, digits.target)

CPU times: user 45.2 s, sys: 4.86 s, total: 50.1 s
Wall time: 8.36 s


array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

# TEST

In [38]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd

In [39]:
iris = load_iris()

In [42]:
l_scores = cross_val_score(LogisticRegression(max_iter=10000), iris.data, iris.target, cv=5)
l_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [43]:
l_scores.mean()

0.9733333333333334

In [45]:
d_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
d_scores


array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [46]:
d_scores.mean()

0.9600000000000002

In [47]:
s_scores = cross_val_score(SVC(), iris.data, iris.target)
s_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [49]:
s_scores.mean()

0.9666666666666666

In [54]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=4), iris.data, iris.target)
r_scores

array([0.96666667, 0.96666667, 0.83333333, 0.96666667, 1.        ])

In [55]:
r_scores.mean()

0.9466666666666667